trigger:
  - main

name: Deploy Bicep files

variables:
  azureServiceConnection: 'MasudaAzureServiceConnection'
  resourceGroupName: 'exampleRGAzureDevOps'
  location: 'eastus'
  templateFile: './main.bicep'

stages:

- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint code
    steps:
      - script: |
          az bicep build --file '$(templateFile)'
        name: LintBicepCode
        displayName: Run Bicep linter
  
  - stage: Validate
    jobs:
      - job: Validate
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              connectedServiceName: '$(azureServiceConnection)'
              location: $(deploymentDefaultLocation)
              deploymentMode: Validation
              resourceGroupName: '$(resourceGroupName)'
              csmFile: '$(templateFile)'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureServiceConnection)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(templateFile)'
              overrideParameters: '-enviroment poc2 -hubVnetEnabled true -spokeVnetEnabled false '
              deploymentMode: 'Incremental'
              deploymentName: 'DeployPipelineTemplate'
