trigger:
- main

name: Deploy Bicep files

variables:

  azureServiceConnection: 'MasudaAzureServiceConnection'
  resourceGroupName: 'exampleRGAzureDevOps'
  location: 'eastus'
  templateFile: './main.bicep'


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    overrideParameters: '-environment poc2 -hubVnetEnabled true-spokeVnetEnabled false '
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
